triggered_at_kst=2026-08-07T10:55:50+09:00
expected_runtime_state=premarket_prep_enabled
expected_cache=kospi-shadow-decision-coach-v5-4-0-r2-static
retry_reason=runtime_fix_latest_missing_after_successful_diagnostic_artifact
